* My custom config for Doom Emacs

See [[https://github.com/hlissner/doom-emacs]] for information about Doom Emacs.

This file is an introduction for my config.

** Optimized features

    * fastest LSP (lsp-bridge)

    * C/C++, Python, Go

    * GitHub Copilot

    * systemd units, rpm spec, Arch Linux pkgbuild

    * build and run single files (mainly for competitive programming) in eshell

    * rime for butter Chinese input

    * ui tweaks and small tools

    * Emacs Application Framework (EAF)

    * Netease Cloud Music

    * matrix chat

** Recommanded enviromment

*** Fedora Linux

Tested with emacs 29 (master branch).

Use pgtk (build with ~--with-pgtk~ argument) for better wayland support.

My copr repo for emacs: [[https://copr.fedorainfracloud.org/coprs/h-cheung/emacs]]

Doom Emacs supports 27.1+ now. 29+ is not supported but in fact works well.

*** Mac OS

** Additional dependencies (check dependencies of Doom Emacs first)

    * fonts

      Sarasa Gothic, Noto Color Emoji (change it in ~:h-cheung ui~)

    * ~librime~, ~emacs-devel~ and rime config in ~$HOME/.local/share/emacs-rime~.
